digital_tube_button_spi:digital_tube_button_spi.o
	gcc -Wall -o digital_tube_button_spi digital_tube_button_spi.c ../../src/BC7278/BC7278.c -lwiringPi -lbcm2835

.PHONY:clean
clean:
	rm -rf *.o digital_tube_button_spi
